[package]
name = "egui-macroquad"
version = "0.7.0"
authors = ["Ilya Sheprut <optozorax@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
homepage = "https://github.com/optozorax/egui-macroquad"
repository = "https://github.com/optozorax/egui-macroquad"
description = "Bindings between egui and macroquad"
readme="README.md"
categories = ["gui", "game-development"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = [
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
]

[dependencies]
egui = { git = "https://github.com/emilk/egui", branch = "master" }
egui-miniquad = { git = "https://github.com/MatthewFrench/egui-miniquad", branch = "master" }
macroquad = { git = "https://github.com/not-fl3/macroquad", branch = "master" }

[dev-dependencies]
egui_demo_lib = { version = "0.15.0", default-features = false }

[profile.release]
opt-level = 2
